# Generated by Django 4.0.5 on 2022-07-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesystem', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=127),
        ),
    ]
