# Generated by Django 4.0.5 on 2022-07-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesystem', '0003_alter_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
