# Generated by Django 4.0.5 on 2022-08-01 03:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesystem', '0009_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetails',
            old_name='usd',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 1, 3, 1, 27, 610134, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
