# Generated by Django 4.0.5 on 2022-08-01 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesystem', '0010_rename_usd_invoicedetails_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicesystem.invoice')),
            ],
        ),
    ]
