# Generated by Django 4.0.5 on 2022-08-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesystem', '0014_tax_invoicesettings_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='amount',
            field=models.FloatField(),
        ),
    ]
