# Generated by Django 4.0.5 on 2022-08-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesystem', '0015_alter_invoicedetails_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesettings',
            name='tax',
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='invoice_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
